name: Hello, World github action workflow

# main 브랜치에 push 이벤트가 발생하면
on:
  push:
    branches: [master]

jobs:
  hello:
    runs-on: ubuntu-20.04

    steps:
      - name: Hello world
        run: echo "Hello, Github Actions!!!"

      - name: Current Date
        run: date

      - name: show current directory contents
        run: ls -al